const fs = require('fs');
const path = require('path');
const { serverCodegen } = require('../node_modules/convex/dist/cjs/cli/codegen_templates/server.js');
const { apiCodegen } = require('../node_modules/convex/dist/cjs/cli/codegen_templates/api.js');

const convexDir = path.resolve(__dirname, '../src/convex');
const genDir = path.join(convexDir, '_generated');
if (!fs.existsSync(genDir)) fs.mkdirSync(genDir, { recursive: true });

// Server codegen
const serverResult = serverCodegen({ useTypeScript: false, envVars: undefined });
fs.writeFileSync(path.join(genDir, 'server.d.ts'), serverResult.DTS);
fs.writeFileSync(path.join(genDir, 'server.js'), serverResult.JS);

// dataModel codegen
const dataModelDTS = `/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.30.0.
 * To regenerate, run \`npx convex dev\`.
 * @module
 */

import type { DataModelFromSchemaDefinition, DocumentByName, TableNamesInDataModel, SystemTableNames } from "convex/server";
import type { GenericId } from "convex/values";
import schema from "../schema.js";

export type TableNames = TableNamesInDataModel<DataModel>;
export type Doc<TableName extends TableNames> = DocumentByName<DataModel, TableName>;
export type Id<TableName extends TableNames | SystemTableNames = TableNames> = GenericId<TableName>;
export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
`;
fs.writeFileSync(path.join(genDir, 'dataModel.d.ts'), dataModelDTS);

// Find all modules in src/convex
const modules = [];
function scan(dir, rel) {
  for (const f of fs.readdirSync(dir, { withFileTypes: true })) {
    if (f.name.startsWith('.') || f.name === '_generated' || f.name === 'node_modules') continue;
    const full = path.join(dir, f.name);
    const subRel = rel ? `${rel}/${f.name}` : f.name;
    if (f.isDirectory()) {
      scan(full, subRel);
    } else if (f.name.endsWith('.ts') && !f.name.endsWith('.d.ts') && !f.name.endsWith('.config.ts') && f.name !== 'schema.ts' && f.name !== 'tsconfig.json') {
      modules.push(subRel);
    }
  }
}
scan(convexDir, '');

const apiResult = apiCodegen(modules, { useTypeScript: false });
fs.writeFileSync(path.join(genDir, 'api.d.ts'), apiResult.DTS);
fs.writeFileSync(path.join(genDir, 'api.js'), apiResult.JS);
console.log('Successfully generated convex _generated files for', modules.length, 'modules');
